on:
  push:
    branches:
      - main
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.5
        with:
          dfx-version: 0.13.1
          install-moc: true
      - run: for i in src/world_engine_backend/*.mo ; do moc --package base $(dfx cache show)/base --check $i ; done
